server_name: "potato annotator"
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
html_layout: "default"
base_html_template: "default"
header_file: "default"
site_dir: "default"
annotation_task_name: "HIPA-AI"
port: 8000
data_files:
  - "C:\\Users\\Zoiya\\OneDrive\\Courses\\Master's Degree\\ARI 510\\Project\\merged_reddit_posts.csv"
item_properties:
  id_key: "created_utc"
  text_key: "selftext"
  context_key: "title"
annotation_codebook_url: "https://1drv.ms/b/s!AjKvun2Ij8a8htpUew_kBR_M_ByVxA?e=CoOPeU"
output_annotation_dir: "C:\\Users\\Zoiya\\OneDrive\\Courses\\Master's Degree\\ARI 510\\Project\\Annotation results"
output_annotation_format: "csv"
annotation_schemes:
  - annotation_type: "radio"
    name: "Patient"
    labels: ["yes", "no"]
    description: "Does this reveal patient features? (Name, Gender, ID, Family, Defining Characteristics)"
  - annotation_type: "radio"
    name: "Visit Characteristics"
    labels: ["yes", "no"]
    description: "Does this reveal visit characteristics? (date/time of visit, treatment, geography)"
  - annotation_type: "radio"
    name: "Healthcare Facility and Staff"
    labels: ["yes", "no"]
    description: "Does this reveal or defame the facility/staff?"
  - annotation_type: "radio"
    name: "Other"
    labels: ["yes", "no"]
    description: "Is it a possible violation even if you answered no to all previous questions?"
